### PR TITLE
Add blocking serial write implementation

### PR DESCRIPTION
**Pull request by hannobraun**
Also adds all blocking traits to the prelude that weren't there already.

There are failign doc tests, but those seem unrelated to this change.

### CODE REVIEW

**Comment by japaric** [comment]
Thanks for the PR, @hannobraun.

I think I would prefer to leave out the implicit `flush` in `bwrite_all` default implementation. I think that would match the behaviour of `std::Write::write*` methods. That also gives the user the option to flush or not.

**Comment by hannobraun** [comment]
Thanks for the feedback, @japaric.

> I think I would prefer to leave out the implicit `flush` in `bwrite_all` default implementation.

I included that deliberately, but I realize now that you're right. I've updated the commits accordingly.

**Comment by japaric** [comment]
Thanks for updating the PR.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2441de6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2441de630b5d00850a608c01a8b92616900be1f1 with merge 59ef38186face51ed88d79069be301a4df5d2ef4...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/embedded-hal/builds/338979917?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 59ef38186face51ed88d79069be301a4df5d2ef4 to master...

**Pull request merged**
