### PR TITLE
remove list of implementations and driver crates from the README ...

### PR DESCRIPTION
**Pull request by japaric**
in favor of the [awesome-embedded-rust] list

[awesome-embedded-rust]: https://github.com/rust-embedded/awesome-embedded-rust

r? @therealprof

### CODE REVIEW

**Comment by therealprof** [comment]
r+

**Comment by therealprof** [comment]
I'll add anything that's missing to [awesome-embedded-rust](https://github.com/rust-embedded/awesome-embedded-rust). Thanks a lot.

**Comment by therealprof** [comment]
@japaric Do you want me to create pull requests or may I edit directly?

**Comment by japaric** [comment]
@therealprof please make pull requests for visibility / transparency

**Pull request merged**
