### PR TITLE
Change traits to take `&mut self`, where appropriate

### PR DESCRIPTION
**Pull request by hannobraun**
This pull request supersedes #16, which seems stalled. It is based on #19. Only the last two commits are actually relevant to this pull request itself. I suggest merging #19 first, then I can rebase this one.

### CODE REVIEW

**Comment by japaric** [comment]
I'll review this after #19 lands.

**Comment by hannobraun** [comment]
Hmm, this is a bit of a mess. Even though I've kept this up to date with the changes in #19, this pull request is still showing 9 commit instead of the 2 that actually differ. "Files changed" also shows the changes from #19, even though those have been merged.

I don't know how to update it, but I guess it's not a big problem. Only the last two commits are relevant. The rest of them have already been merged into master.

**Comment by hannobraun** [comment]
@japaric Is there anything I can do to help this along? Do you want me to open a new pull request for this, to get rid of those commits that were already merged om #19?

**Comment by japaric** [comment]
Sorry I had forgotten about this PR. It LGTM now.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5e2c733 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5e2c7331bcece85a65b0ad71ec94800152e36056 with merge 5aa6d09bf4328d26f96def10277109a050490b2e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/embedded-hal/builds/289160760?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 5aa6d09bf4328d26f96def10277109a050490b2e to master...

**Comment by hannobraun** [comment]
No trouble. Thank you!

**Pull request merged**
