### PR TITLE
make Serial generic over the number of data bits

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit cb609ab has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit cb609ab with merge cb609ab...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/embedded-hal/builds/241638221?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing cb609ab9f3af59dd21f0a6d1f533b207dc613df8 to master...

**Pull request merged**
