### PR TITLE
Add `flush` method to `serial::Write`

### PR DESCRIPTION
**Pull request by hannobraun**
As suggested previously here: https://github.com/japaric/embedded-hal/issues/3#issuecomment-325887412

### CODE REVIEW

**Comment by hannobraun** [comment]
@japaric Is there anything I can do to help this along? This seems like a small change that can be reviewed quickly.

**Comment by hannobraun** [comment]
@japaric I hate to bug you, but have you had a chance to look into this? Anything I can do to get this merged?

**Comment by japaric** [comment]
Thanks for the PR (and for the patience), @hannobraun.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9238350 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9238350077c02732fbeb66d1ec9dc5813a9d836e with merge db91212bb97eb40231560e0621099dd323cbab4c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/embedded-hal/builds/319125137?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing db91212bb97eb40231560e0621099dd323cbab4c to master...

**Comment by hannobraun** [comment]
Thank you!

**Pull request merged**
