### PR TITLE
Fix link in doc comment

### PR DESCRIPTION
**Pull request by hannobraun**
This also fixes a whole bunch of warnings by "cargo doc".

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @hannobraun.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit edb9e9a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit edb9e9a4abf9dffec40afbe5139835a0c42255ae with merge e9386f45e0d9a69a3b4009392cda922d3a44cf78...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/embedded-hal/builds/304756395?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing e9386f45e0d9a69a3b4009392cda922d3a44cf78 to master...

**Comment by hannobraun** [comment]
Thanks for merging!

**Pull request merged**
